# Generated by Django 4.0.1 on 2022-01-21 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='track',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
